import type { Bus } from "./types"

const calculatePrice = (distance: number, busType: string): number => {
  const baseRates = {
    "Non-AC Seater": 1.2,
    "AC Seater": 1.8,
    "AC Semi-Sleeper": 2.2,
    "AC Sleeper": 2.8,
    "Volvo AC": 3.2,
    "Multi-Axle AC": 3.5,
  }

  const rate = baseRates[busType as keyof typeof baseRates] || 2.0
  let price = distance * rate

  // Distance multiplier for longer routes
  if (distance > 800) price *= 1.15
  else if (distance > 500) price *= 1.1

  return Math.round(price)
}

export const cityAliases: Record<string, string[]> = {
  Delhi: ["delhi", "new delhi", "ncr", "nd"],
  Mumbai: ["mumbai", "bombay", "bom"],
  Bengaluru: ["bengaluru", "bangalore", "blr"],
  Chennai: ["chennai", "madras", "maa"],
  Kolkata: ["kolkata", "calcutta", "cal"],
  Hyderabad: ["hyderabad", "hyd", "secunderabad"],
  Pune: ["pune", "poona"],
  Ahmedabad: ["ahmedabad", "amdavad"],
  Jaipur: ["jaipur", "pink city"],
  Surat: ["surat"],
  Lucknow: ["lucknow"],
  Kanpur: ["kanpur"],
  Nagpur: ["nagpur"],
  Indore: ["indore"],
  Thane: ["thane"],
  Bhopal: ["bhopal"],
  Visakhapatnam: ["visakhapatnam", "vizag"],
  Pimpri: ["pimpri", "pimpri chinchwad"],
  Patna: ["patna"],
  Vadodara: ["vadodara", "baroda"],
  Ghaziabad: ["ghaziabad"],
  Ludhiana: ["ludhiana"],
  Agra: ["agra"],
  Nashik: ["nashik"],
  Faridabad: ["faridabad"],
  Meerut: ["meerut"],
  Rajkot: ["rajkot"],
  Kalyan: ["kalyan", "kalyan dombivali"],
  Vasai: ["vasai", "vasai virar"],
  Varanasi: ["varanasi", "banaras"],
  Srinagar: ["srinagar"],
  Aurangabad: ["aurangabad"],
  Dhanbad: ["dhanbad"],
  Amritsar: ["amritsar"],
  "Navi Mumbai": ["navi mumbai", "new mumbai"],
  Allahabad: ["allahabad", "prayagraj"],
  Ranchi: ["ranchi"],
  Howrah: ["howrah"],
  Coimbatore: ["coimbatore"],
  Jabalpur: ["jabalpur"],
  Gwalior: ["gwalior"],
  Vijayawada: ["vijayawada"],
  Jodhpur: ["jodhpur"],
  Madurai: ["madurai"],
  Raipur: ["raipur"],
  Kota: ["kota"],
  Chandigarh: ["chandigarh"],
  Guwahati: ["guwahati"],
  Solapur: ["solapur"],
  Hubli: ["hubli", "hubli dharwad"],
  Tiruchirappalli: ["tiruchirappalli", "trichy"],
  Bareilly: ["bareilly"],
  Mysore: ["mysore", "mysuru"],
  Tiruppur: ["tiruppur"],
  Gurgaon: ["gurgaon", "gurugram"],
  Aligarh: ["aligarh"],
  Jalandhar: ["jalandhar"],
  Bhubaneswar: ["bhubaneswar"],
  Salem: ["salem"],
  Warangal: ["warangal"],
  Guntur: ["guntur"],
  Bhiwandi: ["bhiwandi"],
  Saharanpur: ["saharanpur"],
  Gorakhpur: ["gorakhpur"],
  Bikaner: ["bikaner"],
  Amravati: ["amravati"],
  Noida: ["noida"],
  Jamshedpur: ["jamshedpur"],
  Bhilai: ["bhilai"],
  Cuttack: ["cuttack"],
  Firozabad: ["firozabad"],
  Kochi: ["kochi", "cochin"],
  Nellore: ["nellore"],
  Bhavnagar: ["bhavnagar"],
  Dehradun: ["dehradun"],
  Durgapur: ["durgapur"],
  Asansol: ["asansol"],
  Rourkela: ["rourkela"],
  Nanded: ["nanded"],
  Kolhapur: ["kolhapur"],
  Ajmer: ["ajmer"],
  Akola: ["akola"],
  Gulbarga: ["gulbarga", "kalaburagi"],
  Jamnagar: ["jamnagar"],
  Ujjain: ["ujjain"],
  Loni: ["loni"],
  Siliguri: ["siliguri"],
  Jhansi: ["jhansi"],
  Ulhasnagar: ["ulhasnagar"],
  Jammu: ["jammu"],
  Sangli: ["sangli", "sangli miraj kupwad"],
  Mangalore: ["mangalore", "mangaluru"],
  Erode: ["erode"],
  Belgaum: ["belgaum", "belagavi"],
  Ambattur: ["ambattur"],
  Tirunelveli: ["tirunelveli"],
  Malegaon: ["malegaon"],
  Gaya: ["gaya"],
  Jalgaon: ["jalgaon"],
  Udaipur: ["udaipur"],
  Maheshtala: ["maheshtala"],
}

export const normalizeCityName = (searchTerm: string): string => {
  const normalized = searchTerm.toLowerCase().trim()

  for (const [mainCity, aliases] of Object.entries(cityAliases)) {
    if (aliases.includes(normalized)) {
      return mainCity
    }
  }

  // If no alias found, return capitalized version
  return searchTerm.charAt(0).toUpperCase() + searchTerm.slice(1).toLowerCase()
}

const routes = {
  "Delhi-Mumbai": { distance: 1154, duration: "16h" },
  "Delhi-Bengaluru": { distance: 1742, duration: "24h" },
  "Mumbai-Bengaluru": { distance: 840, duration: "12h" },
  "Bengaluru-Chennai": { distance: 290, duration: "5h" },
  "Delhi-Chennai": { distance: 1768, duration: "26h" },
  "Mumbai-Chennai": { distance: 1028, duration: "15h" },
  "Delhi-Kolkata": { distance: 1305, duration: "18h" },
  "Mumbai-Pune": { distance: 149, duration: "3h" },
  "Delhi-Jaipur": { distance: 280, duration: "5h" },
  "Mumbai-Goa": { distance: 464, duration: "8h" },
  "Bengaluru-Hyderabad": { distance: 569, duration: "8h" },
  "Chennai-Coimbatore": { distance: 507, duration: "7h" },
  "Delhi-Agra": { distance: 233, duration: "4h" },
  "Mumbai-Nashik": { distance: 165, duration: "3h" },
  "Pune-Goa": { distance: 464, duration: "8h" },
  "Hyderabad-Chennai": { distance: 625, duration: "9h" },
  "Kolkata-Bhubaneswar": { distance: 442, duration: "7h" },
  "Ahmedabad-Mumbai": { distance: 524, duration: "8h" },
  "Jaipur-Udaipur": { distance: 421, duration: "6h" },
  "Chennai-Madurai": { distance: 462, duration: "7h" },
  "Delhi-Chandigarh": { distance: 243, duration: "4h" },
  "Mumbai-Indore": { distance: 588, duration: "9h" },
  "Bengaluru-Mysore": { distance: 139, duration: "3h" },
  "Chennai-Pondicherry": { distance: 162, duration: "3h" },
  "Delhi-Lucknow": { distance: 553, duration: "8h" },
  "Mumbai-Aurangabad": { distance: 375, duration: "6h" },
  "Pune-Bengaluru": { distance: 741, duration: "11h" },
  "Hyderabad-Vijayawada": { distance: 275, duration: "4h" },
  "Kolkata-Siliguri": { distance: 561, duration: "8h" },
}

export const mockBuses: Bus[] = [
  // Delhi to Mumbai routes
  {
    id: "bus-001",
    operator: "Ashok Leyland Travels",
    name: "Super Deluxe Express",
    type: "AC Sleeper",
    route: { from: "Delhi", to: "Mumbai" },
    departureTime: "22:30",
    arrivalTime: "14:30",
    price: calculatePrice(1154, "AC Sleeper"),
    availableSeats: 12,
    totalSeats: 40,
    rating: 4.5,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Blanket"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(40).fill("available") },
  },
  {
    id: "bus-002",
    operator: "BharatBenz Express",
    name: "Comfort Plus",
    type: "AC Semi-Sleeper",
    route: { from: "Delhi", to: "Mumbai" },
    departureTime: "20:00",
    arrivalTime: "12:00",
    price: calculatePrice(1154, "AC Semi-Sleeper"),
    availableSeats: 8,
    totalSeats: 35,
    rating: 4.2,
    amenities: ["AC", "WiFi", "Charging Point"],
    seatLayout: { rows: 9, seatsPerRow: 4, layout: Array(35).fill("available") },
  },
  {
    id: "bus-003",
    operator: "Volvo Luxury Lines",
    name: "Premium Coach",
    type: "Volvo AC",
    route: { from: "Delhi", to: "Mumbai" },
    departureTime: "21:15",
    arrivalTime: "13:15",
    price: calculatePrice(1154, "Volvo AC"),
    availableSeats: 15,
    totalSeats: 45,
    rating: 4.7,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Blanket", "Snacks"],
    seatLayout: { rows: 11, seatsPerRow: 4, layout: Array(45).fill("available") },
  },

  // Mumbai to Delhi routes
  {
    id: "bus-004",
    operator: "Tata Motors Express",
    name: "Capital Express",
    type: "AC Sleeper",
    route: { from: "Mumbai", to: "Delhi" },
    departureTime: "21:00",
    arrivalTime: "13:00",
    price: calculatePrice(1154, "AC Sleeper"),
    availableSeats: 18,
    totalSeats: 42,
    rating: 4.3,
    amenities: ["AC", "WiFi", "Charging Point", "Blanket"],
    seatLayout: { rows: 11, seatsPerRow: 4, layout: Array(42).fill("available") },
  },

  // Delhi to Bengaluru routes
  {
    id: "bus-005",
    operator: "South India Express",
    name: "Bangalore Special",
    type: "Multi-Axle AC",
    route: { from: "Delhi", to: "Bengaluru" },
    departureTime: "19:30",
    arrivalTime: "19:30",
    price: calculatePrice(1742, "Multi-Axle AC"),
    availableSeats: 14,
    totalSeats: 44,
    rating: 4.4,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Blanket", "Meals"],
    seatLayout: { rows: 11, seatsPerRow: 4, layout: Array(44).fill("available") },
  },

  // Bengaluru to Delhi routes
  {
    id: "bus-006",
    operator: "North India Travels",
    name: "Delhi Express",
    type: "Volvo AC",
    route: { from: "Bengaluru", to: "Delhi" },
    departureTime: "18:00",
    arrivalTime: "18:00",
    price: calculatePrice(1742, "Volvo AC"),
    availableSeats: 16,
    totalSeats: 40,
    rating: 4.6,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Snacks"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(40).fill("available") },
  },

  // Mumbai to Bengaluru routes
  {
    id: "bus-007",
    operator: "Royal Travels",
    name: "Mumbai Express",
    type: "Multi-Axle AC",
    route: { from: "Mumbai", to: "Bengaluru" },
    departureTime: "21:00",
    arrivalTime: "09:00",
    price: calculatePrice(840, "Multi-Axle AC"),
    availableSeats: 16,
    totalSeats: 44,
    rating: 4.4,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Blanket", "Meals"],
    seatLayout: { rows: 11, seatsPerRow: 4, layout: Array(44).fill("available") },
  },

  // Bengaluru to Mumbai routes
  {
    id: "bus-008",
    operator: "West Coast Express",
    name: "Mumbai Special",
    type: "AC Sleeper",
    route: { from: "Bengaluru", to: "Mumbai" },
    departureTime: "20:30",
    arrivalTime: "08:30",
    price: calculatePrice(840, "AC Sleeper"),
    availableSeats: 12,
    totalSeats: 38,
    rating: 4.2,
    amenities: ["AC", "WiFi", "Charging Point", "Blanket"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(38).fill("available") },
  },

  // Bengaluru to Chennai routes
  {
    id: "bus-009",
    operator: "South India Travels",
    name: "Bangalore Express",
    type: "AC Sleeper",
    route: { from: "Bengaluru", to: "Chennai" },
    departureTime: "23:00",
    arrivalTime: "07:00",
    price: calculatePrice(290, "AC Sleeper"),
    availableSeats: 10,
    totalSeats: 36,
    rating: 4.3,
    amenities: ["AC", "WiFi", "Blanket", "Charging Point"],
    seatLayout: { rows: 9, seatsPerRow: 4, layout: Array(36).fill("available") },
  },
  {
    id: "bus-010",
    operator: "Tamil Nadu Express",
    name: "Metro Connect",
    type: "Volvo AC",
    route: { from: "Bengaluru", to: "Chennai" },
    departureTime: "22:15",
    arrivalTime: "06:15",
    price: calculatePrice(290, "Volvo AC"),
    availableSeats: 14,
    totalSeats: 40,
    rating: 4.6,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Snacks"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(40).fill("available") },
  },

  // Chennai to Bengaluru routes
  {
    id: "bus-011",
    operator: "Karnataka Express",
    name: "Bangalore Bound",
    type: "AC Semi-Sleeper",
    route: { from: "Chennai", to: "Bengaluru" },
    departureTime: "22:00",
    arrivalTime: "06:00",
    price: calculatePrice(290, "AC Semi-Sleeper"),
    availableSeats: 18,
    totalSeats: 35,
    rating: 4.1,
    amenities: ["AC", "WiFi", "Charging Point"],
    seatLayout: { rows: 9, seatsPerRow: 4, layout: Array(35).fill("available") },
  },

  // Mumbai to Pune routes
  {
    id: "bus-012",
    operator: "Orange Travels",
    name: "Intercity Deluxe",
    type: "AC Seater",
    route: { from: "Mumbai", to: "Pune" },
    departureTime: "08:00",
    arrivalTime: "11:00",
    price: calculatePrice(149, "AC Seater"),
    availableSeats: 22,
    totalSeats: 45,
    rating: 4.0,
    amenities: ["AC", "WiFi", "Charging Point"],
    seatLayout: { rows: 12, seatsPerRow: 4, layout: Array(45).fill("available") },
  },
  {
    id: "bus-013",
    operator: "Shivneri Travels",
    name: "Express Connect",
    type: "Volvo AC",
    route: { from: "Mumbai", to: "Pune" },
    departureTime: "09:30",
    arrivalTime: "12:30",
    price: calculatePrice(149, "Volvo AC"),
    availableSeats: 28,
    totalSeats: 40,
    rating: 4.5,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(40).fill("available") },
  },

  // Pune to Mumbai routes
  {
    id: "bus-014",
    operator: "Maharashtra Express",
    name: "Mumbai Connect",
    type: "AC Seater",
    route: { from: "Pune", to: "Mumbai" },
    departureTime: "07:00",
    arrivalTime: "10:00",
    price: calculatePrice(149, "AC Seater"),
    availableSeats: 25,
    totalSeats: 42,
    rating: 4.2,
    amenities: ["AC", "WiFi", "Charging Point"],
    seatLayout: { rows: 11, seatsPerRow: 4, layout: Array(42).fill("available") },
  },

  // Delhi to Jaipur routes
  {
    id: "bus-015",
    operator: "Rajasthan Roadways",
    name: "Pink City Express",
    type: "AC Seater",
    route: { from: "Delhi", to: "Jaipur" },
    departureTime: "06:00",
    arrivalTime: "11:00",
    price: calculatePrice(280, "AC Seater"),
    availableSeats: 30,
    totalSeats: 45,
    rating: 4.1,
    amenities: ["AC", "WiFi", "Charging Point"],
    seatLayout: { rows: 12, seatsPerRow: 4, layout: Array(45).fill("available") },
  },
  {
    id: "bus-016",
    operator: "Royal Rajasthan",
    name: "Heritage Express",
    type: "Volvo AC",
    route: { from: "Delhi", to: "Jaipur" },
    departureTime: "14:30",
    arrivalTime: "19:30",
    price: calculatePrice(280, "Volvo AC"),
    availableSeats: 20,
    totalSeats: 40,
    rating: 4.4,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Snacks"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(40).fill("available") },
  },

  // Jaipur to Delhi routes
  {
    id: "bus-017",
    operator: "Capital Express",
    name: "Delhi Bound",
    type: "AC Semi-Sleeper",
    route: { from: "Jaipur", to: "Delhi" },
    departureTime: "22:00",
    arrivalTime: "03:00",
    price: calculatePrice(280, "AC Semi-Sleeper"),
    availableSeats: 15,
    totalSeats: 35,
    rating: 4.3,
    amenities: ["AC", "WiFi", "Charging Point"],
    seatLayout: { rows: 9, seatsPerRow: 4, layout: Array(35).fill("available") },
  },

  // Mumbai to Goa routes
  {
    id: "bus-018",
    operator: "Konkan Express",
    name: "Goa Special",
    type: "AC Sleeper",
    route: { from: "Mumbai", to: "Goa" },
    departureTime: "21:30",
    arrivalTime: "05:30",
    price: calculatePrice(464, "AC Sleeper"),
    availableSeats: 12,
    totalSeats: 40,
    rating: 4.5,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Blanket"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(40).fill("available") },
  },

  // Goa to Mumbai routes
  {
    id: "bus-019",
    operator: "Coastal Travels",
    name: "Mumbai Express",
    type: "Volvo AC",
    route: { from: "Goa", to: "Mumbai" },
    departureTime: "20:00",
    arrivalTime: "04:00",
    price: calculatePrice(464, "Volvo AC"),
    availableSeats: 18,
    totalSeats: 42,
    rating: 4.3,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Snacks"],
    seatLayout: { rows: 11, seatsPerRow: 4, layout: Array(42).fill("available") },
  },

  // Bengaluru to Hyderabad routes
  {
    id: "bus-020",
    operator: "Telangana Express",
    name: "Hyderabad Connect",
    type: "AC Sleeper",
    route: { from: "Bengaluru", to: "Hyderabad" },
    departureTime: "22:30",
    arrivalTime: "06:30",
    price: calculatePrice(569, "AC Sleeper"),
    availableSeats: 14,
    totalSeats: 38,
    rating: 4.2,
    amenities: ["AC", "WiFi", "Charging Point", "Blanket"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(38).fill("available") },
  },

  // Hyderabad to Bengaluru routes
  {
    id: "bus-021",
    operator: "Deccan Express",
    name: "Bangalore Special",
    type: "Multi-Axle AC",
    route: { from: "Hyderabad", to: "Bengaluru" },
    departureTime: "21:00",
    arrivalTime: "05:00",
    price: calculatePrice(569, "Multi-Axle AC"),
    availableSeats: 16,
    totalSeats: 44,
    rating: 4.4,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Blanket", "Meals"],
    seatLayout: { rows: 11, seatsPerRow: 4, layout: Array(44).fill("available") },
  },

  // Chennai to Coimbatore routes
  {
    id: "bus-022",
    operator: "Tamil Nadu Travels",
    name: "Coimbatore Express",
    type: "AC Seater",
    route: { from: "Chennai", to: "Coimbatore" },
    departureTime: "06:30",
    arrivalTime: "13:30",
    price: calculatePrice(507, "AC Seater"),
    availableSeats: 25,
    totalSeats: 45,
    rating: 4.0,
    amenities: ["AC", "WiFi", "Charging Point"],
    seatLayout: { rows: 12, seatsPerRow: 4, layout: Array(45).fill("available") },
  },

  // Coimbatore to Chennai routes
  {
    id: "bus-023",
    operator: "Western Ghats Express",
    name: "Chennai Connect",
    type: "Volvo AC",
    route: { from: "Coimbatore", to: "Chennai" },
    departureTime: "21:30",
    arrivalTime: "04:30",
    price: calculatePrice(507, "Volvo AC"),
    availableSeats: 20,
    totalSeats: 40,
    rating: 4.3,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point", "Snacks"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(40).fill("available") },
  },

  // Delhi to Chandigarh routes
  {
    id: "bus-024",
    operator: "Punjab Express",
    name: "Chandigarh Special",
    type: "AC Seater",
    route: { from: "Delhi", to: "Chandigarh" },
    departureTime: "07:00",
    arrivalTime: "11:00",
    price: calculatePrice(243, "AC Seater"),
    availableSeats: 28,
    totalSeats: 45,
    rating: 4.2,
    amenities: ["AC", "WiFi", "Charging Point"],
    seatLayout: { rows: 12, seatsPerRow: 4, layout: Array(45).fill("available") },
  },

  // Chandigarh to Delhi routes
  {
    id: "bus-025",
    operator: "Haryana Roadways",
    name: "Delhi Express",
    type: "Volvo AC",
    route: { from: "Chandigarh", to: "Delhi" },
    departureTime: "18:00",
    arrivalTime: "22:00",
    price: calculatePrice(243, "Volvo AC"),
    availableSeats: 22,
    totalSeats: 40,
    rating: 4.4,
    amenities: ["AC", "WiFi", "Entertainment", "Charging Point"],
    seatLayout: { rows: 10, seatsPerRow: 4, layout: Array(40).fill("available") },
  },
]
